version: '3.4'

services:
  # postgres DB
  login_db:
    image: postgres:13.2-alpine
    container_name: login_db
    ports:
        - 15433:5432
    volumes:
        - login_db_volume:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: login_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
        POSTGRES_PORT: "5432"
        #TZ: Asia/Tokyo
    hostname: login_host
    restart: always
    user: root
    networks:
      - backend_bridge

  onlineshop:
    image: ${DOCKER_REGISTRY-}onlineshop
    build:
      context: .
      dockerfile: OnlineShop/Dockerfile
